### PR TITLE
update example with code for version 0.9.0

### PR DESCRIPTION
**Pull request by jjmax75**

### CODE REVIEW

**Comment by golemparts** [comment]
Thank you for the proposed changes. I appreciate the effort!

I'm currently only providing examples for the latest (development) version. Version 0.10.0 will be released within the next few weeks, which is why the README includes example code specifically for that version. All development happens on the master branch, so you might see example code on GitHub for a version that isn't yet available through crates.io. Examples for the latest released version, 0.9.0, can be found at https://crates.io/crates/rppal. You can also download an earlier release from the Releases tab on GitHub, or clone the repo and checkout the release tag. Perhaps I should add a note to the README to clarify.

Unfortunately that means I can't merge this pull request. Please let me know if you have any additional comments or suggestions.

**Comment by jjmax75** [comment]
No problem, thanks for the info

**Comment by golemparts** [comment]
> No problem, thanks for the info

As a side note, if you'd like to try out v0.10.0 (which is stable enough to use, although the interface may still change), you can add a dependency to your `Cargo.toml` for the GitHub repository. As you may have noticed, v0.10.0 has a revamped interface for the gpio module, which adds a bunch of convenience methods, makes it easier to access the GPIO peripheral from different threads, allows multiple Gpio instances, and lets you store (owned) pins in multiple structs. You can check out the documentation for 0.10.0 at https://docs.golemparts.com/rppal/dev/rppal/

**Comment by jjmax75** [comment]
Thanks, it looks interesting, I'll give it a try.

I'm just learning rust and pi at the moment and this library looked like
the most well structured

**Comment by golemparts** [comment]
Thanks, that's good to hear. Rust can be challenging to learn, but as with any language it becomes easier with experience. Let me know if you run into any RPPAL-specific issues and I'll try to help you figure them out.

**Pull request closed without merging**
