### PR TITLE
Update to `embedded_hal` 1.0.

### PR DESCRIPTION
**Pull request by reitermarkus**
Update to the alpha version of `embedded_hal` 1.0.0. Also depend on `linux_embedded_hal` to deduplicate some code.

### CODE REVIEW

**Comment by golemparts** [comment]
Thanks for submitting this PR! Looks good to me. There are two points I'd like to see addressed before I can merge this though:
* 0.2.x compatibility has been removed, which will cause issues with older/abandoned crates. I'd prefer to keep both around at least until after the full 1.0.0 release to give everyone more time to transition. [Here](https://github.com/rust-embedded/embedded-hal#adding-support-for-an-embedded-hal--alpha-version-in-a-hal-implementation) is an example of how to support both.
* Adding a dependency for ```linux_embedded_hal``` (and all of its dependencies) feels unnecessary just for the Delay implementation, considering it just uses ```thread::sleep()``` like rppal currently does, and our implementation is scheduled for a rewrite as mentioned in #40, at which point the dependency would have to be removed anyway.

I'm happy to schedule some time for myself, merge your PR as-is and implement these changes. If you're up for addressing them yourself that'd be great too. In that case let me know so we don't end up both doing the same thing. :)

**Comment by reitermarkus** [comment]
I re-added the implementations for 0.2.x compatibility, except for `Delay`, which I'll leave up to you.

**Comment by reitermarkus** [comment]
Ok, I now also re-added `Delay` using `spin_sleep`.

**Comment by golemparts** [comment]
Awesome! Thanks for implementing the changes.

**Pull request merged**
